---
title: "Survival analysis_HW4"
author: "김민국"
date: '2019_11_25 '
header-includes:
  - \usepackage[hangul]{kotex}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=T, eval=TRUE}
library(survival)
library(KMsurv)
```

```{r echo=T, eval=TRUE}
data("larynx")
data <- larynx
```


```{r echo=T, eval=TRUE}
surv_data <- Surv(time = data$time, event = data$delta)
data_reg_log <- survreg(surv_data ~ factor(stage) + age, dist = "loglogistic", data = data)
summary(data_reg_log)
```

```{r echo=T, eval=TRUE}
## 각 모수들의 추정량
mu_hat <- data_reg_log$coefficients[1]
sigma_hat <- data_reg_log$scale
lamda_hat <- exp(-mu_hat/sigma_hat)
alpha_hat <- 1/sigma_hat

beta_hat <- -data_reg_log$coefficients[2:length(data_reg_log$coefficients)] / sigma_hat
beta_hat
```

```{r echo=T, eval=TRUE}
exp(beta_hat[1])  ## stage1에 비해 stage2 일 때 odds비의 증가분 (odss 비 = s/1-s) 
exp(beta_hat[2])  ## stage1에 비해 stage3 일 때 odds비의 증가분 (odss 비 = s/1-s)
exp(beta_hat[3])  ## stage1에 비해 stage4 일 때 odds비의 증가분 (odss 비 = s/1-s) 
```